# Stage 1: Node client
FROM node:21

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./
COPY package-lock.json ./

# Install client dependencies
RUN npm install

# Copy the client application code to the container
COPY . .

# Build the client app
RUN npm run build

EXPOSE 5173

# Specify the default command to run the application
CMD ["npm", "run", "dev"]



